eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
server:
  port: 8090
spring:

  spring:
    datasource:
      url: jdbc:h2:mem:testdb4
      username: sa
      password: password
      driver-class-name: org.h2.Driver
    h2:
      console:
        enabled: true

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

management:
  tracing:
    sampling:
      probability: 1.0